version: '3.8'
services:
  CarsApiApp:
    image: carsapi
    container_name: CarsApiApp
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: ./CarsApi/Dockerfile
    expose:
      - 5109
    ports:
      - 5109:80
    networks:
      - mybridgenetwork
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - mybridgenetwork
    volumes:
      - mymongovolume:/data/db
    restart: always

  postgresapp:
    image: postgres
    container_name: postgresapp
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=MySecretPass!
    networks:
      - mybridgenetwork
    restart: always

  UsersApiApp:
    image: usersapi
    container_name: UsersApiApp
    build:
      context: .
      dockerfile: ./UsersApi/Dockerfile
    depends_on:
      - postgresapp
    expose:
      - 5111
    ports:
      - 5111:80
    networks:
      - mybridgenetwork
    restart: always

  GatewayApp:
    image: gateway
    container_name: GatewayApp
    depends_on:
      - UsersApiApp
      - CarsApiApp
    expose:
      - 5148
    ports:
      - 5148:80
    build:
      context: .
      dockerfile: ./GatewayApi/Dockerfile
    networks:
      - mybridgenetwork
    restart: always

  redis:
    image: redis
    container_name: redisdb
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - mybridgenetwork
    restart: always

networks:
  mybridgenetwork:
    driver: bridge

volumes:
  mymongovolume:
    driver: local
