version: "3.8"

services:
  webapi1:
    image: mywebapi1
    build:
      context: ./webapi1/
      dockerfile: app.Dockerfile
    container_name: mywebapi1
    environment:
      ASPNETCORE_URLS: http://+:80
    depends_on:
      - webapi2
    ports:
      - 5000:80
    networks:
      - myappnetwork
    restart: always

  webapi2:
    image: mywebapi2
    build:
      context: ./webapi2/
      dockerfile: app.Dockerfile
    container_name: mywebapi2
    environment:
      ASPNETCORE_URLS: http://+:81
    depends_on:
      - postgres
    ports:
      - 5001:81
    networks:
      - myappnetwork
    restart: always
  postgres:
    image: postgres:latest
    container_name: mypostgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: Pass1234!
      POSTGRES_DB: mydb
    volumes:
    - mypostgresdb_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - myappnetwork
    restart: always

networks:
  myappnetwork:
    driver: bridge

volumes:
  mypostgresdb_data:
