version: '3.8'

services:
  consumer:
    build:
      context: ./Consumer/
      dockerfile: dockerfile
    container_name: consumer
    ports:
      - "2000:80"
    networks:
      - mybridge
    environment:
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - rabbit
    restart: always

  producer:
    build:
      context: ./Producer/
      dockerfile: dockerfile
    container_name: producer
    ports:
      - "2001:81"
    networks:
      - mybridge
    environment:
      - ASPNETCORE_URLS=http://+:81
    depends_on:
      - rabbit
    restart: always

  rabbit:
    image: rabbitmq:management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    networks:
      - mybridge
    volumes:
      - rabbit:/var/lib/rabbitmq
    restart: always

networks:
  mybridge: 
   driver: bridge

volumes:
  rabbit:
